version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:338.0.0
    volumes:
      - gcp-creds:/creds
      - .:/staff_profiles
    working_dir: /staff_profiles
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: