# Generated by Django 4.0.4 on 2022-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(default=8988, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
