# Generated by Django 4.0.4 on 2022-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0002_alter_userprofile_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(default=15989, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
