# Generated by Django 4.0.4 on 2022-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_api', '0003_alter_userprofile_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(default=23539, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
